from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy
from django.views.generic import TemplateView

from .forms import (
    CustomAuthenticationForm,
    CustomPasswordChangeForm,
    CustomPasswordResetForm,
    CustomSetPasswordForm,
)
from .views.auth import (
    LoginView,
    PasswordResetView,
    no_org,
    suspended,
)
from .views.settings import (
    agent_page,
    org_allow_user_soul_update,
    org_allowed_models_update,
    org_allowed_transcription_models_update,
    org_budget_update,
    org_description_update,
    org_feature_model_update,
    org_max_context_update,
    org_models_update,
    org_name_update,
    org_settings_page,
    org_skills_update,
    org_pii_scan_toggle_update,
    org_pii_quarantine_toggle_update,
    org_soul_reset,
    org_soul_update,
    org_subagents_update,
    org_tools_update,
    org_transcription_model_update,
    org_usage_page,
    preferences_agent_attach_skills_update,
    preferences_feature_model_update,
    preferences_live_transcription_mode_update,
    preferences_max_context_update,
    preferences_models_update,
    preferences_transcription_model_update,
    profile_page,
    profile_update,
    settings_page,
    soul_reset,
    soul_update,
    theme_update,
    usage_page,
)

app_name = "accounts"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(authentication_form=CustomAuthenticationForm),
        name="login",
    ),
    path("profile/", profile_page, name="profile"),
    path("profile/update/", profile_update, name="profile_update"),
    path("agent/", agent_page, name="agent"),
    path("agent/soul/", soul_update, name="soul_update"),
    path("agent/soul/reset/", soul_reset, name="soul_reset"),
    path("settings/", settings_page, name="settings"),
    path("settings/theme/", theme_update, name="theme_update"),
    path("settings/models/", preferences_models_update, name="preferences_models_update"),
    path("settings/max-context/", preferences_max_context_update, name="preferences_max_context_update"),
    path("settings/transcription-model/", preferences_transcription_model_update, name="preferences_transcription_model_update"),
    path("settings/live-transcription-mode/", preferences_live_transcription_mode_update, name="preferences_live_transcription_mode_update"),
    path("settings/agent-attach-skills/", preferences_agent_attach_skills_update, name="preferences_agent_attach_skills_update"),
    path("settings/feature-model/", preferences_feature_model_update, name="preferences_feature_model_update"),
    path("usage/", usage_page, name="usage"),
    path("org/settings/", org_settings_page, name="org_settings"),
    path("org/settings/allowed-models/", org_allowed_models_update, name="org_allowed_models_update"),
    path("org/settings/models/", org_models_update, name="org_models_update"),
    path("org/settings/tools/", org_tools_update, name="org_tools_update"),
    path("org/settings/skills/", org_skills_update, name="org_skills_update"),
    path("org/settings/subagents/", org_subagents_update, name="org_subagents_update"),
    path("org/settings/pii-scan/", org_pii_scan_toggle_update, name="org_pii_scan_toggle_update"),
    path("org/settings/pii-quarantine/", org_pii_quarantine_toggle_update, name="org_pii_quarantine_toggle_update"),
    path("org/settings/budget/", org_budget_update, name="org_budget_update"),
    path("org/settings/max-context/", org_max_context_update, name="org_max_context_update"),
    path("org/settings/allowed-transcription-models/", org_allowed_transcription_models_update, name="org_allowed_transcription_models_update"),
    path("org/settings/description/", org_description_update, name="org_description_update"),
    path("org/settings/name/", org_name_update, name="org_name_update"),
    path("org/settings/soul/", org_soul_update, name="org_soul_update"),
    path("org/settings/soul/reset/", org_soul_reset, name="org_soul_reset"),
    path("org/settings/allow-user-soul/", org_allow_user_soul_update, name="org_allow_user_soul_update"),
    path("org/settings/transcription-model/", org_transcription_model_update, name="org_transcription_model_update"),
    path("org/settings/feature-model/", org_feature_model_update, name="org_feature_model_update"),
    path("org/usage/", org_usage_page, name="org_usage"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            form_class=CustomPasswordChangeForm,
            success_url=reverse_lazy("accounts:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            form_class=CustomPasswordResetForm,
            success_url=reverse_lazy("accounts:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            form_class=CustomSetPasswordForm,
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path("suspended/", suspended, name="suspended"),
    path("no-org/", no_org, name="no_org"),
    path(
        "logged-out/",
        TemplateView.as_view(template_name="registration/logged_out.html"),
        name="logged_out",
    ),
    path("", include("django.contrib.auth.urls")),
]
