# Generated by Django 6.0.1 on 2026-03-11 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_migrate_theme_to_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('instructions', models.TextField()),
                ('tool_names', models.JSONField(blank=True, default=list)),
                ('level', models.CharField(choices=[('system', 'System'), ('org', 'Organization'), ('user', 'User')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_skills', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_skills', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='agent_skills.agentskill')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('level', 'system')), fields=('slug',), name='unique_system_skill_slug'), models.UniqueConstraint(condition=models.Q(('level', 'org')), fields=('slug', 'organization'), name='unique_org_skill_slug'), models.UniqueConstraint(condition=models.Q(('level', 'user')), fields=('slug', 'created_by'), name='unique_user_skill_slug'), models.CheckConstraint(condition=models.Q(models.Q(('level', 'system'), _negated=True), models.Q(('created_by__isnull', True), ('organization__isnull', True)), _connector='OR'), name='system_skill_no_owner'), models.CheckConstraint(condition=models.Q(models.Q(('level', 'org'), _negated=True), ('organization__isnull', False), _connector='OR'), name='org_skill_has_org'), models.CheckConstraint(condition=models.Q(models.Q(('level', 'user'), _negated=True), ('created_by__isnull', False), _connector='OR'), name='user_skill_has_creator')],
            },
        ),
    ]
