# Generated by Django 6.0.1 on 2026-04-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_skills', '0002_skilltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentskill',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
