# Generated by Django 6.0.1 on 2026-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_skills', '0003_agentskill_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentskill',
            name='instructions',
            field=models.TextField(max_length=75000),
        ),
    ]
