# Generated by Django 6.0.1 on 2026-06-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_skills', '0004_alter_agentskill_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentskill',
            name='audience',
            field=models.CharField(choices=[('main', 'Main agent'), ('subagent', 'Sub-agent'), ('shared', 'Shared')], default='main', max_length=10),
        ),
    ]
