# Generated by Django 6.0.1 on 2026-09-13 05:49

import agent_skills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_skills', '0007_alter_skillresource_original_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillresource',
            name='optimized_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=agent_skills.models.skill_resource_upload_path),
        ),
    ]
