# Generated by Django 6.0.1 on 2026-10-05 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_usersettings_theme'),
        ('agent_skills', '0010_agentskill_slug_customized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentskill',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentskill',
            name='share_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentskill',
            name='share_requested_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_skill_shares', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='agentskill',
            constraint=models.CheckConstraint(condition=models.Q(('share_requested_org__isnull', True), ('level', 'user'), _connector='OR'), name='share_request_user_tier'),
        ),
    ]
