# Generated by Django 6.0.1 on 2026-03-05 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('summary_token_count', models.PositiveIntegerField(default=0)),
                ('summary_up_to_message_id', models.UUIDField(blank=True, null=True)),
                ('summary_message_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatThreadDataRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('data_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_links', to='documents.dataroom')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_data_rooms', to='chat.chatthread')),
            ],
            options={
                'ordering': ['attached_at'],
                'unique_together': {('thread', 'data_room')},
            },
        ),
        migrations.AddField(
            model_name='chatthread',
            name='data_rooms',
            field=models.ManyToManyField(blank=True, related_name='chat_threads', through='chat.ChatThreadDataRoom', to='documents.dataroom'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=10)),
                ('content', models.TextField()),
                ('tool_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatthread')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='chat_chatme_thread__b4c881_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['created_by', '-updated_at'], name='chat_chatth_created_ccac15_idx'),
        ),
    ]
