# Generated by Django 6.0.1 on 2026-03-13 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('prompt', models.TextField()),
                ('skill_slug', models.CharField(blank=True, max_length=64)),
                ('model_tier', models.CharField(default='mid', max_length=10)),
                ('model_used', models.CharField(blank=True, max_length=128)),
                ('blocking', models.BooleanField(default=False)),
                ('data_room_ids', models.JSONField(default=list)),
                ('tool_names', models.JSONField(default=list)),
                ('result', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subagent_runs', to='chat.chatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subagent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='chat_subage_user_id_ae8764_idx'), models.Index(fields=['thread', '-created_at'], name='chat_subage_thread__e28fcf_idx')],
            },
        ),
    ]
