# Generated by Django 6.0.1 on 2026-03-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='token_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='summary_message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='summary_token_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='summary_up_to_message_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
