# Generated by Django 6.0.1 on 2026-03-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatcanvas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('original', 'Original'), ('ai_edit', 'AI Edit'), ('user_save', 'User Save'), ('import', 'Import'), ('restore', 'Restore')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='chat.chatcanvas')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='chatcanvas',
            name='accepted_checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.canvascheckpoint'),
        ),
        migrations.AddIndex(
            model_name='canvascheckpoint',
            index=models.Index(fields=['canvas', 'order'], name='chat_canvas_canvas__d48b51_idx'),
        ),
    ]
