# Generated by Django 6.0.1 on 2026-03-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_backfill_token_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
