# Generated by Django 6.0.1 on 2026-03-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_skills', '0001_initial'),
        ('chat', '0003_canvascheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='agent_skills.agentskill'),
        ),
    ]
