# Generated by Django 6.0.1 on 2026-03-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_multicanvas'),
        ('chat', '0003_threadtask'),
    ]

    operations = [
    ]
