# Generated by Django 6.0.1 on 2026-03-16 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_multicanvas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=50)),
                ('size_bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='chatcanvas',
            new_name='chat_chatca_thread__a98f07_idx',
            old_name='chat_chatcanvas_thread_created_idx',
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatattachment',
            index=models.Index(fields=['thread', 'created_at'], name='chat_chatat_thread__1d8b56_idx'),
        ),
        migrations.AddIndex(
            model_name='chatattachment',
            index=models.Index(fields=['message'], name='chat_chatat_message_3b7180_idx'),
        ),
    ]
