# Generated by Django 6.0.1 on 2026-03-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatattachment'),
        ('chat', '0004_merge_0003_multicanvas_0003_threadtask'),
    ]

    operations = [
    ]
