# Generated by Django 6.0.1 on 2026-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_merge_20260316_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subagentrun',
            name='blocking',
        ),
        migrations.AddField(
            model_name='subagentrun',
            name='timeout',
            field=models.PositiveIntegerField(default=0, help_text='Seconds the tool waited for the result (0=fire-and-forget)'),
        ),
    ]
