# Generated by Django 6.0.1 on 2026-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_add_result_delivered_to_subagentrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
