# Generated by Django 6.0.1 on 2026-03-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_add_thread_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatattachment',
            name='content_type',
            field=models.CharField(max_length=100),
        ),
    ]
