# Generated by Django 6.0.1 on 2026-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_widen_attachment_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_redacted',
            field=models.BooleanField(default=False),
        ),
    ]
