# Generated by Django 6.0.1 on 2026-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_is_redacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvascheckpoint',
            name='source',
            field=models.CharField(choices=[('original', 'Original'), ('ai_edit', 'AI Edit'), ('user_save', 'User Save'), ('import', 'Import'), ('restore', 'Restore'), ('redacted', 'Redacted')], max_length=20),
        ),
    ]
