# Generated by Django 6.0.1 on 2026-04-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_canvas_checkpoint_redacted_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_hidden_from_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
