# Generated by Django 6.0.1 on 2026-05-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_fix_subagent_result_messages'),
        ('documents', '0003_dataroomdocument_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadChunkUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_usages', to='documents.dataroomdocumentchunk')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_usages', to='documents.dataroomdocument')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_usages', to='chat.chatthread')),
            ],
            options={
                'indexes': [models.Index(fields=['document'], name='threadchunkusage_doc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('chunk__isnull', False)), fields=('thread', 'chunk'), name='unique_thread_chunk_usage')],
            },
        ),
    ]
