# Generated by Django 6.0.1 on 2026-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_threadchunkusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
