# Generated by Django 6.0.1 on 2026-06-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_backfill_chatthread_retain_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagentrun',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subagentrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
