# Generated by Django 6.0.1 on 2026-06-16 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_subagentrun_reported_at_subagentrun_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('history_mode', models.CharField(choices=[('fresh', 'Fresh each run'), ('conversational', 'Conversational')], default='fresh', max_length=16)),
                ('cadence_kind', models.CharField(choices=[('interval', 'Interval'), ('clock', 'Clock')], default='interval', max_length=16)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('clock_time', models.TimeField(blank=True, null=True)),
                ('clock_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly')], default='', max_length=16)),
                ('clock_weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tz', models.CharField(default='UTC', max_length=64)),
                ('next_run', models.DateTimeField(db_index=True)),
                ('max_runs', models.PositiveIntegerField(default=10)),
                ('runs_completed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], db_index=True, default='active', max_length=8)),
                ('running', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_result_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_errors', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loops', to=settings.AUTH_USER_MODEL)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loop', to='chat.chatthread')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_run'], name='chat_loop_status_7b18a5_idx'), models.Index(fields=['created_by', '-last_result_at'], name='chat_loop_created_647a9a_idx')],
            },
        ),
    ]
