# Generated by Django 6.0.1 on 2026-06-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='model',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
