# Generated by Django 6.0.1 on 2026-06-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_chatthread_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='max_runs',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
