# Generated by Django 6.0.1 on 2026-06-19 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_drop_thread_skill_fk'),
        ('documents', '0015_backfill_vector_version_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blob', models.FileField(max_length=500, upload_to='image_assets/%Y/%m/')),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('alt_text', models.CharField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='chat.chatcanvas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='chat.chatmessage')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='documents.dataroomdocumentversion')),
            ],
            options={
                'indexes': [models.Index(fields=['version'], name='chat_imagea_version_415b00_idx'), models.Index(fields=['canvas'], name='chat_imagea_canvas__93554c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('canvas__isnull', True), ('message__isnull', True), ('version__isnull', False)), models.Q(('canvas__isnull', False), ('message__isnull', True), ('version__isnull', True)), models.Q(('canvas__isnull', True), ('message__isnull', False), ('version__isnull', True)), _connector='OR'), name='imageasset_exactly_one_owner')],
            },
        ),
    ]
