# Generated by Django 6.0.1 on 2026-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_imageasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='blob',
            field=models.FileField(blank=True, max_length=500, upload_to='image_assets/%Y/%m/'),
        ),
    ]
