# Generated by Django 6.0.1 on 2026-06-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_loop_max_runs_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcanvas',
            name='dr_save_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
