# Generated by Django 6.0.1 on 2026-06-22 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_chatcanvas_dr_save_attempts'),
        ('documents', '0015_backfill_vector_version_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imageasset',
            name='imageasset_exactly_one_owner',
        ),
        migrations.AddField(
            model_name='imageasset',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='chat.chatthread'),
        ),
        migrations.AddIndex(
            model_name='imageasset',
            index=models.Index(fields=['thread'], name='chat_imagea_thread__3821f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='imageasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('canvas__isnull', True), ('message__isnull', True), ('thread__isnull', True), ('version__isnull', False)), models.Q(('canvas__isnull', False), ('message__isnull', True), ('thread__isnull', True), ('version__isnull', True)), models.Q(('canvas__isnull', True), ('message__isnull', False), ('thread__isnull', True), ('version__isnull', True)), models.Q(('canvas__isnull', True), ('message__isnull', True), ('thread__isnull', False), ('version__isnull', True)), _connector='OR'), name='imageasset_exactly_one_owner'),
        ),
    ]
