# Generated by Django 6.0.1 on 2026-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_imageasset_thread_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='extracted_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
