# Generated by Django 6.0.1 on 2026-06-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_rename_imageasset_to_asset_add_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatcanvas',
            name='unique_canvas_title_per_thread',
        ),
        migrations.AddField(
            model_name='chatcanvas',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='chatcanvas',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('thread', 'title'), name='unique_canvas_title_per_thread'),
        ),
    ]
