# Generated by Django 6.0.1 on 2026-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_chatcanvas_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagentrun',
            name='canvas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subagentrun',
            name='canvas_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
