# Generated by Django 6.0.1 on 2026-08-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_alter_loop_max_runs_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source_page_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
