# Generated by Django 6.0.1 on 2026-08-21 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_asset_source_page_url_asset_source_url'),
        ('documents', '0016_alter_dataroomdocumentversion_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_id', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('sent', 'Sent'), ('orphaned', 'Orphaned')], db_index=True, default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_id', models.CharField(max_length=32)),
                ('content_hash', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('rendered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlideRenderRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('agent_preview', 'Agent preview'), ('user_preview', 'User preview'), ('pdf_export', 'PDF export')], max_length=16)),
                ('slide_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlideSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Untitled deck', max_length=255)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('base_template', models.CharField(blank=True, default='wilfred_default', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('last_activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideSetCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('original', 'Original'), ('ai_edit', 'AI Edit'), ('user_save', 'User Save'), ('restore', 'Restore'), ('redacted', 'Redacted')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='asset',
            name='imageasset_exactly_one_owner',
        ),
        migrations.AddField(
            model_name='slidecomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sliderender',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.asset'),
        ),
        migrations.AddField(
            model_name='slideset',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_sets', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='sliderenderrun',
            name='slide_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_runs', to='chat.slideset'),
        ),
        migrations.AddField(
            model_name='sliderender',
            name='slide_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='chat.slideset'),
        ),
        migrations.AddField(
            model_name='slidecomment',
            name='slide_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chat.slideset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='slide_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='chat.slideset'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['slide_set'], name='chat_asset_slide_s_9e9013_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('canvas__isnull', True), ('message__isnull', True), ('slide_set__isnull', True), ('thread__isnull', True), ('version__isnull', False)), models.Q(('canvas__isnull', False), ('message__isnull', True), ('slide_set__isnull', True), ('thread__isnull', True), ('version__isnull', True)), models.Q(('canvas__isnull', True), ('message__isnull', False), ('slide_set__isnull', True), ('thread__isnull', True), ('version__isnull', True)), models.Q(('canvas__isnull', True), ('message__isnull', True), ('slide_set__isnull', True), ('thread__isnull', False), ('version__isnull', True)), models.Q(('canvas__isnull', True), ('message__isnull', True), ('slide_set__isnull', False), ('thread__isnull', True), ('version__isnull', True)), _connector='OR'), name='imageasset_exactly_one_owner'),
        ),
        migrations.AddField(
            model_name='slidesetcheckpoint',
            name='slide_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='chat.slideset'),
        ),
        migrations.AddIndex(
            model_name='slideset',
            index=models.Index(fields=['thread', 'created_at'], name='chat_slides_thread__128fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='slideset',
            index=models.Index(fields=['thread', 'is_active', '-last_activated_at'], name='chat_slides_thread__c4592b_idx'),
        ),
        migrations.AddConstraint(
            model_name='slideset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('thread', 'title'), name='unique_slideset_title_per_thread'),
        ),
        migrations.AddIndex(
            model_name='sliderenderrun',
            index=models.Index(fields=['slide_set', 'created_at'], name='chat_slider_slide_s_98b6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='sliderenderrun',
            index=models.Index(fields=['status', 'created_at'], name='chat_slider_status_8ad125_idx'),
        ),
        migrations.AddIndex(
            model_name='sliderender',
            index=models.Index(fields=['slide_set', 'slide_id'], name='chat_slider_slide_s_cd73fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='sliderender',
            constraint=models.UniqueConstraint(fields=('slide_set', 'slide_id'), name='unique_slide_render_per_slide'),
        ),
        migrations.AddIndex(
            model_name='slidecomment',
            index=models.Index(fields=['slide_set', 'slide_id'], name='chat_slidec_slide_s_c1aa19_idx'),
        ),
        migrations.AddIndex(
            model_name='slidesetcheckpoint',
            index=models.Index(fields=['slide_set', 'order'], name='chat_slides_slide_s_23676f_idx'),
        ),
    ]
