# Generated by Django 6.0.1 on 2026-09-08 07:13

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_dispatched_at(apps, schema_editor):
    # Rows the pre-queue code already handed to Celery must count as
    # slot-holders from the first dispatcher tick, not as waiting in line.
    SubAgentRun = apps.get_model("chat", "SubAgentRun")
    SubAgentRun.objects.filter(
        status="pending", dispatched_at__isnull=True,
    ).exclude(celery_task_id="").update(dispatched_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_slidecomment_sliderender_sliderenderrun_slideset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subagentrun',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='subagentrun',
            index=models.Index(fields=['status', 'created_at'], name='chat_subage_status_82e9a4_idx'),
        ),
        migrations.RunPython(backfill_dispatched_at, reverse_code=migrations.RunPython.noop),
    ]
