# Generated by Django 6.0.1 on 2026-09-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_subagentrun_dispatched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='scratchpad',
            field=models.TextField(blank=True, default=''),
        ),
    ]
