# Generated by Django 6.0.1 on 2026-09-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_chatthread_scratchpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagentrun',
            name='scratchpad',
            field=models.TextField(blank=True, default=''),
        ),
    ]
