# Generated by Django 6.0.1 on 2026-09-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_subagentrun_scratchpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthreadskill',
            name='attached_by',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=8),
        ),
    ]
