# Generated by Django 6.0.1 on 2026-09-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0042_chatthreadskill_attached_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
