# Generated by Django 6.0.1 on 2026-09-25 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0043_chatattachment_page_count'),
        ('documents', '0023_dataroomdocumentversion_page_render'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='role',
            field=models.CharField(choices=[('embedded', 'embedded'), ('page_render', 'page_render')], db_index=True, default='embedded', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'page_render')), fields=('version', 'page_number'), name='asset_unique_page_render_per_version'),
        ),
    ]
