# Generated by Django 6.0.1 on 2026-09-26 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0044_asset_role_page_number'),
        ('documents', '0023_dataroomdocumentversion_page_render'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='imageasset_exactly_one_owner',
        ),
        migrations.AddField(
            model_name='asset',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='chat.chatattachment'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='page_render_state',
            field=models.CharField(choices=[('none', 'Not rendered'), ('pending', 'Rendering'), ('partial', 'Partially rendered'), ('ready', 'Rendered'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='processing_state',
            field=models.CharField(choices=[('pending', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='ready', max_length=10),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['attachment'], name='chat_asset_attachm_0f8657_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attachment__isnull', True), ('canvas__isnull', True), ('message__isnull', True), ('slide_set__isnull', True), ('thread__isnull', True), ('version__isnull', False)), models.Q(('attachment__isnull', True), ('canvas__isnull', False), ('message__isnull', True), ('slide_set__isnull', True), ('thread__isnull', True), ('version__isnull', True)), models.Q(('attachment__isnull', True), ('canvas__isnull', True), ('message__isnull', False), ('slide_set__isnull', True), ('thread__isnull', True), ('version__isnull', True)), models.Q(('attachment__isnull', True), ('canvas__isnull', True), ('message__isnull', True), ('slide_set__isnull', True), ('thread__isnull', False), ('version__isnull', True)), models.Q(('attachment__isnull', True), ('canvas__isnull', True), ('message__isnull', True), ('slide_set__isnull', False), ('thread__isnull', True), ('version__isnull', True)), models.Q(('attachment__isnull', False), ('canvas__isnull', True), ('message__isnull', True), ('slide_set__isnull', True), ('thread__isnull', True), ('version__isnull', True)), _connector='OR'), name='imageasset_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'page_render')), fields=('attachment', 'page_number'), name='asset_unique_page_render_per_attachment'),
        ),
    ]
