# Generated by Django 6.0.1 on 2026-10-01 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0045_attachment_processing_and_asset_owner'),
        ('documents', '0023_dataroomdocumentversion_page_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcanvas',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.dataroomdocument'),
        ),
        migrations.AddField(
            model_name='chatcanvas',
            name='truncated_from_chars',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
