# Generated by Django 6.0.1 on 2026-10-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0046_canvas_truncation_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagentrun',
            name='shared_canvases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
