# Generated by Django 6.0.1 on 2026-10-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0047_subagentrun_shared_canvases'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagentrun',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
