# Generated by Django 6.0.1 on 2026-10-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0048_subagentrun_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='email_ordinal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='chat.chatattachment'),
        ),
    ]
