# Generated by Django 6.0.1 on 2026-10-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0049_chatattachment_email_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to='chat_attachments/%Y/%m/'),
        ),
    ]
