# Generated by Django 6.0.1 on 2026-03-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
