# Generated by Django 6.0.1 on 2026-06-03 08:06

from django.db import migrations, models


def _assert_single_membership(apps, schema_editor):
    """Fail loudly if any user has more than one membership.

    The unique constraint added below would otherwise raise an opaque
    IntegrityError mid-migration. This surfaces the offending users instead.
    """
    from django.db.models import Count

    Membership = apps.get_model("accounts", "Membership")
    dupes = list(
        Membership.objects.values("user")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .values_list("user", flat=True)
    )
    if dupes:
        raise RuntimeError(
            f"Users with multiple memberships, resolve first: {dupes}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_enable_system_skills_for_existing_orgs"),
    ]

    operations = [
        migrations.RunPython(
            _assert_single_membership, migrations.RunPython.noop
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_membership_per_user"
            ),
        ),
    ]
