# Generated by Django 6.0.1 on 2026-06-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membership_unique_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='soul',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='user',
            name='soul',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
