# Generated by Django 6.0.1 on 2026-06-11 06:11

import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def lowercase_emails(apps, schema_editor):
    """Lowercase all stored emails so the CI-unique constraint can be added.

    Fails loudly (rolling back the whole migration) if two accounts collide
    case-insensitively — that must be resolved by hand. Only user IDs are
    reported, never emails (logging policy).
    """
    User = apps.get_model("accounts", "User")

    collisions = (
        User.objects.annotate(email_ci=Lower("email"))
        .values("email_ci")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    if collisions.exists():
        ids = list(
            User.objects.annotate(email_ci=Lower("email"))
            .filter(email_ci__in=[c["email_ci"] for c in collisions])
            .values_list("id", flat=True)
        )
        raise RuntimeError(
            "Cannot lowercase emails: case-insensitive duplicates exist for "
            f"user ids {sorted(ids)}. Merge or rename those accounts, then re-run."
        )

    # Bulk statement; no signals fire (historical models have no receivers).
    User.objects.exclude(email=Lower("email")).update(email=Lower("email"))


def backfill_theme(apps, schema_editor):
    """Copy the legacy UserSettings.theme CharField into preferences["theme"]
    where the key is missing, making the preferences JSON the canonical store
    (readers fall back to the CharField only for rows this never touched)."""
    UserSettings = apps.get_model("accounts", "UserSettings")

    for us in UserSettings.objects.all().iterator():
        prefs = us.preferences or {}
        if not prefs.get("theme"):
            prefs["theme"] = us.theme or "light"
            us.preferences = prefs
            us.save(update_fields=["preferences"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_soul_user_soul_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Order matters: data fix first so a collision surfaces as the loud
        # RuntimeError above, not an opaque IntegrityError from the constraint.
        migrations.RunPython(lowercase_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique', violation_error_message='A user with this email already exists.'),
        ),
        migrations.RunPython(backfill_theme, migrations.RunPython.noop),
        # Drops only the redundant explicit index (unique already indexes).
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
