# Generated by Django 6.0.1 on 2026-06-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_email_ci_unique_theme_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, upload_to='user_avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_original',
            field=models.ImageField(blank=True, max_length=500, upload_to='user_avatars/originals/%Y/%m/'),
        ),
    ]
