# Generated by Django 6.0.1 on 2026-06-23 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_profile_picture_user_profile_picture_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=128)),
                ('family_norm', models.CharField(db_index=True, max_length=128)),
                ('source', models.CharField(choices=[('upload', 'upload'), ('google', 'google')], default='upload', max_length=16)),
                ('blob', models.FileField(max_length=500, upload_to='fonts/%Y/%m/')),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('font_format', models.CharField(blank=True, default='', max_length=16)),
                ('weight', models.PositiveIntegerField(default=400)),
                ('style', models.CharField(choices=[('normal', 'normal'), ('italic', 'italic')], default='normal', max_length=8)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('embeddable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='font_assets', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'family_norm'], name='accounts_fo_organiz_9bac8f_idx'), models.Index(fields=['source', 'family_norm'], name='accounts_fo_source_52cf54_idx')],
            },
        ),
    ]
