# Generated by Django 6.0.1 on 2026-06-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fontasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, upload_to='org_logos/%Y/%m/'),
        ),
    ]
