# Generated by Django 6.0.1 on 2026-06-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='soul',
            field=models.TextField(blank=True, default='', max_length=75000),
        ),
        migrations.AlterField(
            model_name='user',
            name='soul',
            field=models.TextField(blank=True, default='', max_length=75000),
        ),
    ]
