# Generated by Django 6.0.1 on 2026-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_soul_max_length_75000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='soul',
            field=models.TextField(blank=True, default='', max_length=25000),
        ),
        migrations.AlterField(
            model_name='user',
            name='soul',
            field=models.TextField(blank=True, default='', max_length=25000),
        ),
    ]
