# Generated by Django 6.0.1 on 2026-08-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_soul_max_length_25000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('system', 'System'), ('dark', 'Dark')], default='system', max_length=10),
        ),
    ]
