# Generated by Django 6.0.1 on 2026-04-08 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0012_chatmessage_is_hidden_from_user_chatthread_metadata'),
        ('documents', '0003_dataroomdocument_transcript'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('agenda', models.TextField(blank=True, default='')),
                ('participants', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live_transcribing', 'Live transcribing'), ('interrupted', 'Interrupted'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('transcript', models.TextField(blank=True, default='')),
                ('transcript_source', models.CharField(blank=True, choices=[('live', 'Live transcription'), ('audio_upload', 'Audio upload'), ('text_upload', 'Text upload')], default='', max_length=16)),
                ('transcription_model', models.CharField(blank=True, default='', max_length=128)),
                ('transcription_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MeetingDataRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('data_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_links', to='documents.dataroom')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_data_rooms', to='meetings.meeting')),
            ],
            options={
                'ordering': ['attached_at'],
                'unique_together': {('meeting', 'data_room')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='data_rooms',
            field=models.ManyToManyField(blank=True, related_name='meetings', through='meetings.MeetingDataRoom', to='documents.dataroom'),
        ),
        migrations.CreateModel(
            name='MeetingTranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.PositiveIntegerField()),
                ('start_offset_seconds', models.FloatField(default=0.0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('transcription_model', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='meetings.meeting')),
            ],
            options={
                'ordering': ['meeting', 'segment_index'],
            },
        ),
        migrations.CreateModel(
            name='MeetingArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('minutes', 'Minutes'), ('summary', 'Summary'), ('notes', 'Notes')], default='minutes', max_length=12)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content_md', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_artifacts', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='meetings.meeting')),
                ('source_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_artifacts', to='chat.chatthread')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['meeting', '-created_at'], name='meetings_me_meeting_de1ed9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to='meeting_attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='meetings.meeting')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['meeting', '-uploaded_at'], name='meetings_me_meeting_280420_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['created_by', '-updated_at'], name='meetings_me_created_ecd3cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingtranscriptsegment',
            constraint=models.UniqueConstraint(fields=('meeting', 'segment_index'), name='meetings_segment_unique_per_meeting'),
        ),
    ]
