# Generated by Django 6.0.1 on 2026-04-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcript_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
