# Generated by Django 6.0.1 on 2026-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_transcript_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcription_chunks_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='transcription_chunks_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
