# Generated by Django 6.0.1 on 2026-04-10 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_skills', '0002_skilltemplate'),
        ('meetings', '0003_meeting_transcription_chunks_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='summarizer_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_as_summarizer', to='agent_skills.agentskill'),
        ),
    ]
