# Generated by Django 6.0.1 on 2026-04-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_summarizer_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='forced_language',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
