# Generated by Django 6.0.1 on 2026-05-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_forced_language'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meetingartifact',
            name='meetings_me_meeting_de1ed9_idx',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='data_rooms',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='summarizer_skill',
        ),
        migrations.RemoveField(
            model_name='meetingartifact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meetingartifact',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meetingartifact',
            name='source_thread',
        ),
        migrations.DeleteModel(
            name='MeetingDataRoom',
        ),
        migrations.DeleteModel(
            name='MeetingArtifact',
        ),
    ]
