# Generated by Django 6.0.1 on 2026-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_remove_meetingartifact_meetings_me_meeting_de1ed9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
