# Generated by Django 6.0.1 on 2026-06-10 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_backfill_meeting_retain_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['created_by', 'status'], name='meetings_me_created_e43cbd_idx'),
        ),
    ]
