# Generated by Django 6.0.1 on 2026-07-04 07:48

from django.conf import settings
from django.db import migrations, models


def dedupe_live_transcriptions(apps, schema_editor):
    """Resolve any pre-existing duplicate live transcriptions per user.

    The new partial unique index (one LIVE_TRANSCRIBING meeting per created_by)
    would abort at CREATE UNIQUE INDEX time if a user already has more than one.
    Keep the most-recently-updated live meeting per user and mark the rest
    INTERRUPTED (the transcript content is valid — same treatment as the stale
    live-source sweeper). Uses .update() to bypass Meeting.save().
    """
    Meeting = apps.get_model("meetings", "Meeting")
    live = (
        Meeting.objects.filter(status="live_transcribing")
        .order_by("created_by_id", "-updated_at")
    )
    seen: set = set()
    stale_pks: list = []
    for pk, created_by_id in live.values_list("pk", "created_by_id"):
        if created_by_id in seen:
            stale_pks.append(pk)
        else:
            seen.add(created_by_id)
    if stale_pks:
        Meeting.objects.filter(pk__in=stale_pks).update(status="interrupted")


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_meeting_meetings_me_created_e43cbd_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_live_transcriptions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'live_transcribing')), fields=('created_by',), name='meetings_one_live_transcription_per_user'),
        ),
    ]
