# Generated by Django 6.0.1 on 2026-03-12 07:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataRoomDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(blank=True, max_length=500, upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('parser_type', models.CharField(blank=True, max_length=64)),
                ('chunking_strategy', models.CharField(blank=True, max_length=64)),
                ('embedding_model', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('doc_index', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.dataroom')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRoomDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=512, null=True)),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField()),
                ('source_page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('source_offset_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_offset_end', models.PositiveIntegerField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.dataroomdocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='DataRoomDocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='documents.dataroomdocument')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddConstraint(
            model_name='dataroomdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_index__gt', 0)), fields=('data_room', 'doc_index'), name='documents_unique_doc_index_per_data_room'),
        ),
        migrations.AddIndex(
            model_name='dataroomdocumentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='documents_d_documen_a04548_idx'),
        ),
        migrations.AddIndex(
            model_name='dataroomdocumentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_vector_gin'),
        ),
        migrations.AddConstraint(
            model_name='dataroomdocumentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='documents_chunk_unique_per_document'),
        ),
        migrations.AddConstraint(
            model_name='dataroomdocumenttag',
            constraint=models.UniqueConstraint(fields=('document', 'key'), name='documents_tag_unique_per_document'),
        ),
    ]
