# Generated by Django 6.0.1 on 2026-03-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dataroomdocumentchunk',
            name='documents_chunk_unique_per_document',
        ),
        migrations.AddField(
            model_name='dataroomdocumentchunk',
            name='is_child',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='dataroomdocumentchunk',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.dataroomdocumentchunk'),
        ),
        migrations.AddConstraint(
            model_name='dataroomdocumentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index', 'is_child'), name='documents_chunk_unique_per_document'),
        ),
    ]
