# Generated by Django 6.0.1 on 2026-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='token_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
