# Generated by Django 6.0.1 on 2026-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocumentchunk',
            name='is_quarantined',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='dataroomdocumentchunk',
            name='quarantine_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
