# Generated by Django 6.0.1 on 2026-02-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_document_token_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='created_at',
        ),
    ]
