# Generated by Django 6.0.1 on 2026-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_guardrails_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocument',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dataroomdocument',
            name='transcription_model',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
