# Generated by Django 6.0.1 on 2026-05-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_dataroomdocument_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataroom',
            name='is_shared',
        ),
    ]
