# Generated by Django 6.0.1 on 2026-05-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_backfill_dataroom_retain_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocument',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataroomdocument',
            name='file_metadata_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
