# Generated by Django 6.0.1 on 2026-03-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_add_doc_index_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
