# Generated by Django 6.0.1 on 2026-06-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_dataroomdocument_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocument',
            name='is_partially_quarantined',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='dataroomdocument',
            name='is_quarantined',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='dataroomdocument',
            name='quarantine_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
