# Generated by Django 6.0.1 on 2026-06-10 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_dataroomdocument_is_partially_quarantined_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dataroomdocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('scanning', 'Scanning'), ('scan_failed', 'Scan failed'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='dataroom',
            constraint=models.UniqueConstraint(fields=('created_by', 'slug'), name='documents_unique_slug_per_user'),
        ),
    ]
