# Generated by Django 6.0.1 on 2026-06-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_dataroom_slug_alter_dataroomdocument_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocumentchunk',
            name='guardrail_scan_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('heuristic_done', 'Heuristic Done'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
