# Generated by Django 6.0.1 on 2026-06-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_dataroomdocumentchunk_guardrail_scan_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocument',
            name='requeue_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
