# Generated by Django 6.0.1 on 2026-06-17 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_dataroomdocument_requeue_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocument',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='DataRoomDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_index', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(choices=[('uploaded', 'Uploaded'), ('agent_created', 'Agent created'), ('canvas_export', 'Canvas export'), ('user_edit', 'User edit'), ('restore', 'Restore')], default='uploaded', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('scanning', 'Scanning'), ('scan_failed', 'Scan failed'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('native_blob', models.FileField(blank=True, max_length=500, upload_to='documents/%Y/%m/')),
                ('native_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_searchable', models.BooleanField(db_index=True, default=False)),
                ('is_quarantined', models.BooleanField(db_index=True, default=False)),
                ('is_partially_quarantined', models.BooleanField(db_index=True, default=False)),
                ('quarantine_reason', models.TextField(blank=True, default='')),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('requeue_count', models.PositiveSmallIntegerField(default=0)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('parser_type', models.CharField(blank=True, max_length=64)),
                ('chunking_strategy', models.CharField(blank=True, max_length=64)),
                ('embedding_model', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.dataroomdocument')),
            ],
            options={
                'ordering': ['document', 'version_index'],
            },
        ),
        migrations.AddField(
            model_name='dataroomdocument',
            name='active_searchable_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.dataroomdocumentversion'),
        ),
        migrations.AddField(
            model_name='dataroomdocument',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.dataroomdocumentversion'),
        ),
        migrations.AddField(
            model_name='dataroomdocumentchunk',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_chunks', to='documents.dataroomdocumentversion'),
        ),
        migrations.AddField(
            model_name='dataroomdocumenttag',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_tags', to='documents.dataroomdocumentversion'),
        ),
        migrations.AddIndex(
            model_name='dataroomdocumentversion',
            index=models.Index(fields=['document', 'version_index'], name='documents_d_documen_8cf0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='dataroomdocumentversion',
            index=models.Index(fields=['document', 'is_searchable'], name='documents_d_documen_a34c7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='dataroomdocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_index'), name='documents_version_unique_per_document'),
        ),
    ]
