# Generated by Django 6.0.1 on 2026-07-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_backfill_vector_version_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomdocumentversion',
            name='origin',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('agent_created', 'Agent created'), ('canvas_export', 'Canvas export'), ('restore', 'Restore')], default='uploaded', max_length=20),
        ),
    ]
