# Generated by Django 6.0.1 on 2026-08-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_alter_dataroomdocumentversion_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocumentversion',
            name='processing_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
