# Generated by Django 6.0.1 on 2026-08-31 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_dataroomdocumentversion_processing_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocument',
            name='content_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='dataroomdocument',
            index=models.Index(fields=['data_room', 'content_sha256'], name='documents_doc_room_sha_idx'),
        ),
    ]
