# Generated by Django 6.0.1 on 2026-09-09 10:36

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_queue_fields(apps, schema_editor):
    # Versions the pre-gate code already handed to Celery (or that are mid-
    # pipeline) must count as slot-holders from the first dispatcher tick, not
    # as waiting in line — otherwise the dispatcher would double-publish them.
    # Terminal and retry-marker rows stay NULL (they hold no slot).
    Version = apps.get_model("documents", "DataRoomDocumentVersion")
    Version.objects.filter(
        status__in=["uploaded", "processing", "scanning"],
    ).update(queued_at=F("created_at"), dispatched_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_dataroomdocument_content_sha256_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocumentversion',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataroomdocumentversion',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dataroomdocumentversion',
            index=models.Index(fields=['status', 'queued_at'], name='documents_d_status_b2c597_idx'),
        ),
        migrations.RunPython(backfill_queue_fields, reverse_code=migrations.RunPython.noop),
    ]
