# Generated by Django 6.0.1 on 2026-09-10 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_version_dispatch_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocumentversion',
            name='quarantine_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='PIIReviewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('org_id', models.IntegerField(blank=True, null=True)),
                ('window_index', models.PositiveIntegerField(default=0)),
                ('document_title', models.CharField(blank=True, default='', max_length=255)),
                ('candidate_categories', models.JSONField(blank=True, default=list)),
                ('action', models.CharField(choices=[('confirmed', 'Confirmed'), ('dismissed', 'Dismissed'), ('fallback', 'Fallback')], max_length=20)),
                ('article_9', models.BooleanField(default=False)),
                ('article_10', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('findings', models.TextField(blank=True, default='')),
                ('excerpt', models.TextField(blank=True, default='')),
                ('retain_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pii_review_events', to='documents.dataroom')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pii_review_events', to='documents.dataroomdocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='documents_p_action_d777b4_idx'), models.Index(fields=['org_id', '-created_at'], name='documents_p_org_id_952894_idx')],
            },
        ),
    ]
