# Generated by Django 6.0.1 on 2026-09-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_dataroomdocumentversion_quarantine_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomdocumentversion',
            name='origin',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('agent_created', 'Agent created'), ('canvas_export', 'Canvas export'), ('restore', 'Restore'), ('user_edited', 'User edited')], default='uploaded', max_length=20),
        ),
    ]
