# Generated by Django 6.0.1 on 2026-09-17 12:35

from django.db import migrations, models


def backfill_quarantine_detail(apps, schema_editor):
    """Populate the new document-level ``quarantine_detail`` for existing
    quarantined documents, mirroring recompute_document_sensitivity: copy from
    the earliest quarantined version carrying a (non-empty) quarantine_reason.
    Few rows in every environment, so a plain loop is fine.
    """
    DataRoomDocument = apps.get_model("documents", "DataRoomDocument")
    DataRoomDocumentVersion = apps.get_model("documents", "DataRoomDocumentVersion")
    for doc in DataRoomDocument.objects.filter(is_quarantined=True):
        v = (
            DataRoomDocumentVersion.objects.filter(document_id=doc.id, is_quarantined=True)
            .exclude(quarantine_reason="")
            .order_by("version_index")
            .first()
        )
        detail = v.quarantine_detail if v else ""
        if detail:
            DataRoomDocument.objects.filter(pk=doc.id).update(quarantine_detail=detail)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_alter_dataroomdocumentversion_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocument',
            name='quarantine_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(backfill_quarantine_detail, migrations.RunPython.noop),
    ]
