# Generated by Django 6.0.1 on 2026-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_dataroomdocument_quarantine_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocumentversion',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataroomdocumentversion',
            name='page_render_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataroomdocumentversion',
            name='page_render_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dataroomdocumentversion',
            name='page_render_state',
            field=models.CharField(choices=[('none', 'Not rendered'), ('pending', 'Rendering'), ('partial', 'Partially rendered'), ('ready', 'Rendered'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='none', max_length=10),
        ),
    ]
