"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import ssl
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _get_env_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


load_dotenv(BASE_DIR / ".env")

# SECURITY: DEBUG defaults to False. Set DJANGO_DEBUG=True only for local development.
DEBUG = _get_env_bool(os.environ.get("DJANGO_DEBUG"), False)

# SECURITY: SECRET_KEY must be set in production (no fallback when DEBUG is False).
_secret_key = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if _secret_key:
    SECRET_KEY = _secret_key
elif DEBUG:
    SECRET_KEY = "django-insecure-dev-only-do-not-use-in-production"
else:
    raise ImproperlyConfigured(
        "Set DJANGO_SECRET_KEY in the environment for production. "
        "Generate one with: python -c \"import secrets; print(secrets.token_urlsafe(50))\""
    )

_allowed_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]
else:
    # Default: local dev + Heroku (*.herokuapp.com). Override with DJANGO_ALLOWED_HOSTS for custom domains.
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", ".herokuapp.com"]

INTERNAL_IPS = [
    "127.0.0.1",
]

# CSRF: required for HTTPS form POSTs (Django 4.0+). Set e.g. DJANGO_CSRF_TRUSTED_ORIGINS=https://your-app.herokuapp.com
_csrf_origins = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]

# Email backend (set before INSTALLED_APPS so we can conditionally add anymail)
EMAIL_BACKEND = os.getenv(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
USING_ANYMAIL = EMAIL_BACKEND.startswith("anymail.backends.")

# Application definition

INSTALLED_APPS = [
    "daphne",  # Must be first to enable ASGI runserver with WebSocket support
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "compressor",
    "core.apps.CoreConfig",
    "accounts",
    "llm_service.apps.LlmServiceConfig",
    "llm_chat.apps.LlmChatConfig",
]
if DEBUG:
    INSTALLED_APPS.extend([
        "debug_toolbar",
        "django_extensions",
        "django_browser_reload",
    ])
if USING_ANYMAIL:
    INSTALLED_APPS.append("anymail")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
if DEBUG:
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.theme',
            ],
        },
    },
]

ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    # Production / Heroku: use Postgres from DATABASE_URL (SSL and options from URL).
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Local development: SQLite.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

AUTH_USER_MODEL = 'accounts.User'

COMPRESS_ROOT = STATIC_ROOT  # So compressed output is under staticfiles and WhiteNoise can serve it
COMPRESS_ENABLED = True
# Offline manifest often misses keys when template context differs between release and runtime; use on-the-fly compression.
COMPRESS_OFFLINE = False

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

LOGIN_REDIRECT_URL = '/chat/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Email: safe defaults and optional prefix/admins
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "webmaster@localhost")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = os.getenv("EMAIL_SUBJECT_PREFIX", "")
ADMINS = []  # e.g. [("Admin", "admin@example.com")]

EMAIL_SENDING_ENABLED = _get_env_bool(os.environ.get("EMAIL_SENDING_ENABLED"), False)

if USING_ANYMAIL:
    ANYMAIL = {
        "MAILGUN_API_KEY": os.getenv("MAILGUN_API_KEY", ""),
        "MAILGUN_SENDER_DOMAIN": os.getenv("MAILGUN_SENDER_DOMAIN", ""),
        "MAILGUN_API_URL": os.getenv("MAILGUN_API_URL", ""),
    }

PASSWORD_RESET_TIMEOUT = int(os.environ.get("DJANGO_PASSWORD_RESET_TIMEOUT", "3600"))

# Email verification (24 hours in seconds)
EMAIL_VERIFICATION_TIMEOUT = int(os.environ.get("EMAIL_VERIFICATION_TIMEOUT", "86400"))
EMAIL_VERIFICATION_REQUIRED = _get_env_bool(
    os.environ.get("EMAIL_VERIFICATION_REQUIRED"), True
)

# Fail-fast validation for production real email
if not DEBUG:
    SAFE_EMAIL_BACKENDS = {
        "django.core.mail.backends.console.EmailBackend",
        "django.core.mail.backends.locmem.EmailBackend",
        "django.core.mail.backends.filebased.EmailBackend",
    }
    is_real_sending_backend = EMAIL_BACKEND not in SAFE_EMAIL_BACKENDS

    if is_real_sending_backend and not EMAIL_SENDING_ENABLED:
        raise ImproperlyConfigured(
            "EMAIL_SENDING_ENABLED must be true to use a real email backend in production."
        )

    if is_real_sending_backend and "@" not in DEFAULT_FROM_EMAIL:
        raise ImproperlyConfigured(
            "DEFAULT_FROM_EMAIL must be set to a valid address in production."
        )

    if USING_ANYMAIL and EMAIL_BACKEND == "anymail.backends.mailgun.EmailBackend":
        if not (ANYMAIL.get("MAILGUN_API_KEY") and ANYMAIL.get("MAILGUN_SENDER_DOMAIN")):
            raise ImproperlyConfigured(
                "Mailgun is selected but MAILGUN_API_KEY and MAILGUN_SENDER_DOMAIN must be set."
            )

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# LLM Service (LiteLLM)
LLM_DEFAULT_MODEL = os.environ.get("LLM_DEFAULT_MODEL", "openai/gpt-5.2")
LLM_ALLOWED_MODELS = [
    m.strip()
    for m in os.environ.get(
        "LLM_ALLOWED_MODELS",
        (
            "openai/gpt-5.2,openai/gpt-5-mini,openai/gpt-5-nano,"
            "anthropic/claude-sonnet-4-5-20250929,anthropic/claude-opus-4-1-20250805,anthropic/claude-3-5-haiku-20241022,"
            "gemini/gemini-3-pro-preview,gemini/gemini-3-flash-preview,gemini/gemini-2.5-pro,gemini/gemini-2.5-flash,gemini/gemini-2.5-flash-lite,"
            "moonshot/kimi-k2.5,moonshot/kimi-k2-thinking"
        ),
    ).split(",")
    if m.strip()
]
LLM_REQUEST_TIMEOUT = float(os.environ.get("LLM_REQUEST_TIMEOUT", "60"))
LLM_MAX_RETRIES = int(os.environ.get("LLM_MAX_RETRIES", "2"))
LLM_LOG_WRITE_TIMEOUT = float(os.environ.get("LLM_LOG_WRITE_TIMEOUT", "5"))
# Optional: list of callables for guardrails (pre: LLMRequest, post: LLMResult)
# LLM_PRE_CALL_HOOKS = []
# LLM_POST_CALL_HOOKS = []

# Channels / Redis
_redis_url = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")
# Heroku Redis (rediss://) uses TLS with a cert that fails default verification; skip for channel layer.
if _redis_url.startswith("rediss://"):
    _channel_hosts = [{"address": _redis_url, "ssl_cert_reqs": ssl.CERT_NONE}]
else:
    _channel_hosts = [_redis_url]
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": _channel_hosts},
    },
}
