# Generated by Django 6.0.1 on 2026-03-20 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_guardrails_foundation'),
        ('chat', '0009_widen_attachment_content_type'),
        ('llm', '0003_remove_llmcalllog_raw_prompt_llmcalllog_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardrailEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_source', models.CharField(choices=[('user_message', 'User Message'), ('document_chunk', 'Document Chunk'), ('web_content', 'Web Content'), ('tool_result', 'Tool Result')], max_length=20)),
                ('check_type', models.CharField(choices=[('heuristic', 'Heuristic'), ('classifier', 'Classifier'), ('llm_review', 'LLM Review')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('action_taken', models.CharField(choices=[('logged', 'Logged'), ('warned', 'Warned'), ('blocked', 'Blocked'), ('escalated', 'Escalated'), ('suspended', 'Suspended'), ('dismissed', 'Dismissed')], max_length=20)),
                ('raw_input', models.TextField()),
                ('reviewer_output', models.TextField(blank=True, null=True)),
                ('llm_call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardrail_events', to='llm.llmcalllog')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardrail_events', to='accounts.organization')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='guardrails.guardrailevent')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardrail_events', to='chat.chatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardrail_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='guardrails__user_id_786441_idx'), models.Index(fields=['organization', '-created_at'], name='guardrails__organiz_e0f5d4_idx'), models.Index(fields=['action_taken', '-created_at'], name='guardrails__action__2debad_idx')],
            },
        ),
    ]
