# Generated by Django 6.0.1 on 2026-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardrails', '0001_guardrails_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardrailevent',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
