# Generated by Django 6.0.1 on 2026-08-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardrails', '0003_backfill_guardrailevent_retain_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardrailevent',
            name='trigger_source',
            field=models.CharField(choices=[('user_message', 'User Message'), ('document_chunk', 'Document Chunk'), ('web_content', 'Web Content'), ('tool_result', 'Tool Result'), ('identity_field', 'Identity Field')], max_length=20),
        ),
    ]
