# Generated by Django 6.0.1 on 2026-09-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardrails', '0004_alter_guardrailevent_trigger_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardrailevent',
            name='trigger_source',
            field=models.CharField(choices=[('user_message', 'User Message'), ('document_chunk', 'Document Chunk'), ('web_content', 'Web Content'), ('tool_result', 'Tool Result'), ('identity_field', 'Identity Field'), ('skill_resource', 'Skill Resource')], max_length=20),
        ),
    ]
