"""Unit tests for documents.services.spreadsheets (reader, headers, mesh,
chunks, manifest). Fixture workbooks are generated by openpyxl inside the
tests — no binary fixtures. Pure-function tests use SimpleTestCase (no DB).
"""
from __future__ import annotations

import datetime
import tempfile
import unittest
from pathlib import Path

from django.test import SimpleTestCase, override_settings

from documents.services.spreadsheets import chunks as chunks_mod
from documents.services.spreadsheets import manifest as manifest_mod
from documents.services.spreadsheets import mesh as mesh_mod
from documents.services.spreadsheets.headers import HeaderInfo, detect_headers
from documents.services.spreadsheets.model import (
    SheetModel,
    col_index,
    col_letter,
    format_cell_value,
    load_workbook_model,
    parse_range,
)


def _save(wb, tmpdir: str, name: str = "book.xlsx") -> Path:
    path = Path(tmpdir) / name
    wb.save(path)
    return path


def _basic_workbook():
    from openpyxl import Workbook

    wb = Workbook()
    ws = wb.active
    ws.title = "Data"
    ws.append(["Name", "Amount", "Status"])
    ws.append(["Alpha", 1234.5, "ACTIVE"])
    ws.append(["Beta", 0.15, "TERMINATED"])
    return wb


class CoordinateHelperTests(SimpleTestCase):
    def test_col_letter_roundtrip(self):
        for index, letters in [(1, "A"), (26, "Z"), (27, "AA"), (52, "AZ"), (703, "AAA")]:
            self.assertEqual(col_letter(index), letters)
            self.assertEqual(col_index(letters), index)

    def test_parse_range(self):
        self.assertEqual(parse_range("A1:C4"), (1, 1, 4, 3))
        self.assertEqual(parse_range("B7"), (7, 2, 7, 2))
        self.assertEqual(parse_range("$B$7:$D$9"), (7, 2, 9, 4))
        with self.assertRaises(ValueError):
            parse_range("nope")


class FormatCellValueTests(SimpleTestCase):
    def test_format_table(self):
        cases = [
            (42, "General", "42"),
            (1234.5, "General", "1234.5"),
            (1234.5, "#,##0.00", "1,234.50"),
            (-1234.5, "#,##0.00", "-1,234.50"),
            (0.15, "0%", "15%"),
            (0.1234, "0.00%", "12.34%"),
            (99.5, '"$"#,##0.00', "$99.50"),
            (1000, '#,##0.00" kr"', "1,000.00 kr"),
            (42, "@", "42"),
            (1234.5, "0.00E+00", "1234.5"),  # scientific: general fallback
            (True, "General", "TRUE"),
            ("abc\x00def", "General", "abcdef"),
            (datetime.datetime(2026, 1, 5), "yyyy-mm-dd", "2026-01-05"),
            (datetime.datetime(2026, 1, 5, 14, 30), "yyyy-mm-dd hh:mm", "2026-01-05 14:30"),
            (datetime.time(9, 5), "hh:mm", "09:05"),
            (None, "General", ""),
        ]
        for value, fmt, expected in cases:
            with self.subTest(value=value, fmt=fmt):
                self.assertEqual(format_cell_value(value, fmt), expected)

    def test_date_format_on_raw_number_falls_back(self):
        # openpyxl normally converts these to datetime; a raw number with a
        # date picture must not be mangled into digits-of-a-date.
        self.assertEqual(format_cell_value(45000, "yyyy-mm-dd"), "45000")


class LoadWorkbookModelTests(SimpleTestCase):
    def test_reads_values_structure_and_formats(self):
        from openpyxl import Workbook
        from openpyxl.formatting.rule import CellIsRule
        from openpyxl.styles import PatternFill

        wb = Workbook()
        ws = wb.active
        ws.title = "Main"
        ws.append(["Name", "Amount", "Status", "Hidden"])
        ws.append(["Alpha", 1234.5, "ACTIVE", "x"])
        ws["B2"].number_format = "#,##0.00"
        ws.append(["Beta", 0.15, "TERMINATED", "y"])
        ws["B3"].number_format = "0%"
        ws["A4"] = "Merged label"
        ws.merge_cells("A4:C4")
        ws["B5"] = "=B2*2"  # no cached value under data_only
        ws["A6"] = "hidden row value"
        ws.column_dimensions["A"].width = 10.57
        ws.column_dimensions["B"].width = 34.71
        ws.column_dimensions["D"].hidden = True
        ws.row_dimensions[3].height = 30
        ws.row_dimensions[6].hidden = True
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = "A1:C3"
        fill = PatternFill(start_color="FFC000", end_color="FFC000", fill_type="solid")
        ws.conditional_formatting.add(
            "C2:C10", CellIsRule(operator="equal", formula=['"TERMINATED"'], fill=fill)
        )
        hidden_sheet = wb.create_sheet("Secret")
        hidden_sheet["A1"] = "hidden"
        hidden_sheet.sheet_state = "hidden"

        with tempfile.TemporaryDirectory() as tmpdir:
            model = load_workbook_model(_save(wb, tmpdir))

        self.assertEqual(len(model.sheets), 1)
        self.assertEqual(model.hidden_sheets, ["Secret"])
        sheet = model.sheets[0]
        self.assertEqual(sheet.name, "Main")

        rows = dict(sheet.rows)
        # Formatted values, original coordinates.
        self.assertIn((2, "1,234.50"), rows[2])
        self.assertIn((2, "15%"), rows[3])
        # Hidden column D and hidden row 6 dropped; formula with no cached
        # value dropped.
        self.assertNotIn(4, [c for cells in rows.values() for c, _ in cells])
        self.assertNotIn(6, rows)
        self.assertNotIn(5, rows)
        # Structure from the XML supplement.
        self.assertEqual(sheet.col_widths[1], 10.57)
        self.assertEqual(sheet.col_widths[2], 34.71)
        self.assertEqual(sheet.hidden_cols, {4})
        self.assertEqual(sheet.hidden_rows, {6})
        self.assertEqual(sheet.row_heights[3], 30.0)
        self.assertIn((4, 1, 4, 3), sheet.merged)
        self.assertEqual(sheet.freeze_rows, 1)
        self.assertEqual(sheet.freeze_cols, 0)
        self.assertEqual(sheet.auto_filter, (1, 1, 3, 3))
        # cellIs CF evaluated during streaming.
        self.assertEqual(sheet.cf_fills.get((3, 3)), "#FFC000")
        self.assertNotIn((2, 3), sheet.cf_fills)

    def test_numeric_cf_rule(self):
        from openpyxl import Workbook
        from openpyxl.formatting.rule import CellIsRule
        from openpyxl.styles import PatternFill

        wb = Workbook()
        ws = wb.active
        ws.append(["v"])
        ws.append([5])
        ws.append([50])
        fill = PatternFill(start_color="FF0000", end_color="FF0000", fill_type="solid")
        ws.conditional_formatting.add(
            "A2:A10", CellIsRule(operator="greaterThan", formula=["10"], fill=fill)
        )
        with tempfile.TemporaryDirectory() as tmpdir:
            model = load_workbook_model(_save(wb, tmpdir))
        sheet = model.sheets[0]
        self.assertEqual(sheet.cf_fills.get((3, 1)), "#FF0000")
        self.assertNotIn((2, 1), sheet.cf_fills)

    def test_table_column_names_extracted(self):
        from openpyxl import Workbook
        from openpyxl.worksheet.table import Table

        wb = Workbook()
        ws = wb.active
        ws.append(["Number", "Project name", "Responsible"])
        ws.append([1, "Alpha", "kari"])
        ws.add_table(Table(displayName="Projects", ref="A1:C2"))
        with tempfile.TemporaryDirectory() as tmpdir:
            model = load_workbook_model(_save(wb, tmpdir))
        tables = model.sheets[0].tables
        self.assertEqual(len(tables), 1)
        self.assertEqual(tables[0].bounds, (1, 1, 2, 3))
        self.assertEqual(tables[0].column_names, ["Number", "Project name", "Responsible"])

    @override_settings(XLSX_MAX_CELLS=5)
    def test_cell_budget_rejects(self):
        from openpyxl import Workbook

        wb = Workbook()
        ws = wb.active
        for i in range(4):
            ws.append([f"a{i}", f"b{i}", f"c{i}"])
        with tempfile.TemporaryDirectory() as tmpdir:
            path = _save(wb, tmpdir)
            with self.assertRaisesMessage(ValueError, "too large"):
                load_workbook_model(path)

    @override_settings(XLSX_MAX_UNCOMPRESSED_BYTES=10)
    def test_zip_budget_rejects(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = _save(_basic_workbook(), tmpdir)
            with self.assertRaisesMessage(ValueError, "too large"):
                load_workbook_model(path)

    def test_non_zip_rejected(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "junk.xlsx"
            path.write_bytes(b"this is not a zip file")
            with self.assertRaisesMessage(ValueError, "not a valid Excel workbook"):
                load_workbook_model(path)

    @override_settings(XLSX_MAX_SHEETS=1)
    def test_sheet_cap_records_skipped(self):
        from openpyxl import Workbook

        wb = Workbook()
        wb.active.append(["a"])
        wb.create_sheet("Second").append(["b"])
        with tempfile.TemporaryDirectory() as tmpdir:
            model = load_workbook_model(_save(wb, tmpdir))
        self.assertEqual(len(model.sheets), 1)
        self.assertEqual(model.skipped_sheets, ["Second"])

    @override_settings(XLSX_MAX_CELL_CHARS=10)
    def test_cell_text_truncated(self):
        from openpyxl import Workbook

        wb = Workbook()
        wb.active["A1"] = "x" * 50
        with tempfile.TemporaryDirectory() as tmpdir:
            model = load_workbook_model(_save(wb, tmpdir))
        text = model.sheets[0].rows[0][1][0][1]
        self.assertEqual(len(text), 10)
        self.assertTrue(text.endswith("…"))


def _sheet(rows, **kwargs) -> SheetModel:
    """Synthetic SheetModel: rows as {excel_row: {col: text}}."""
    sheet = SheetModel(name=kwargs.pop("name", "S"), index=kwargs.pop("index", 0))
    for key, value in kwargs.items():
        setattr(sheet, key, value)
    for r in sorted(rows):
        cells = sorted(rows[r].items())
        sheet.rows.append((r, [(c, t) for c, t in cells]))
        sheet.max_data_row = max(sheet.max_data_row, r)
        sheet.max_data_col = max([sheet.max_data_col] + [c for c, _ in cells])
        sheet.cell_count += len(cells)
    return sheet


class DetectHeadersTests(SimpleTestCase):
    def test_table_signal_wins(self):
        from documents.services.spreadsheets.model import TableInfo

        sheet = _sheet(
            {1: {1: "colA", 2: "colB"}, 2: {1: "1", 2: "2"}},
            tables=[TableInfo(name="T", bounds=(1, 1, 2, 2), header_row_count=1,
                              column_names=["Number", "Name"])],
            auto_filter=(1, 1, 2, 2),
        )
        info = detect_headers(sheet)
        self.assertEqual((info.signal, info.confidence), ("table", "definitive"))
        self.assertEqual(info.header_row, 1)
        self.assertEqual(info.labels, {1: "Number", 2: "Name"})

    def test_autofilter_signal(self):
        sheet = _sheet(
            {2: {1: "Name", 2: "Amount"}, 3: {1: "a", 2: "1"}},
            auto_filter=(2, 1, 3, 2),
        )
        info = detect_headers(sheet)
        self.assertEqual(info.signal, "autofilter")
        self.assertEqual(info.header_row, 2)
        self.assertEqual(info.labels[1], "Name")

    def test_freeze_rows_signal(self):
        sheet = _sheet({1: {1: "H1"}, 2: {1: "v"}}, freeze_rows=1)
        info = detect_headers(sheet)
        self.assertEqual(info.signal, "freeze")
        self.assertEqual(info.header_row, 1)

    def test_frozen_column_marks_transposed(self):
        sheet = _sheet({1: {1: "Label", 2: "v1"}}, freeze_cols=1)
        info = detect_headers(sheet)
        self.assertEqual(info.signal, "freeze_col")
        self.assertTrue(info.transposed)
        self.assertIsNone(info.header_row)

    def test_type_profile(self):
        sheet = _sheet({
            1: {1: "Name", 2: "Amount", 3: "Year"},
            2: {1: "a", 2: "1", 3: "2020"},
            3: {1: "b", 2: "2", 3: "2021"},
        })
        sheet.type_profile = [(1, 3, 3), (2, 3, 1), (3, 3, 1)]
        info = detect_headers(sheet)
        self.assertEqual(info.signal, "type_profile")
        self.assertEqual(info.header_row, 1)

    def test_positional_fallback_and_letter_labels(self):
        sheet = _sheet({1: {1: "1", 2: "2"}, 2: {1: "3", 2: "4"}})
        sheet.type_profile = [(1, 2, 0), (2, 2, 0)]
        info = detect_headers(sheet)
        self.assertEqual((info.signal, info.confidence), ("positional", "low"))
        self.assertEqual(info.label_for(2), "Column B")

    def test_empty_sheet(self):
        self.assertEqual(detect_headers(_sheet({})).signal, "empty")


class MeshPlanTests(SimpleTestCase):
    def test_verified_width_samples(self):
        self.assertEqual(mesh_mod.excel_width_to_px(10.57), 79)
        self.assertEqual(mesh_mod.excel_width_to_px(34.71), 248)
        self.assertEqual(mesh_mod.excel_width_to_px(8.43), 64)
        self.assertEqual(mesh_mod.points_to_px(15), 20)

    def test_width_clamps(self):
        self.assertEqual(mesh_mod.excel_width_to_px(1), mesh_mod.MIN_COL_PX)
        self.assertEqual(mesh_mod.excel_width_to_px(200), mesh_mod.MAX_COL_PX)

    def _plan(self, widths, n_rows=5, text_len=3, header_row=None):
        rows = {
            r: {c: "x" * text_len for c in range(1, len(widths) + 1)}
            for r in range(1, n_rows + 1)
        }
        sheet = _sheet(rows, col_widths={i + 1: w for i, w in enumerate(widths) if w})
        return mesh_mod.plan_sheet_mesh(sheet, header_row)

    def test_snap_scales_small_overflow(self):
        # px: 420+420+300+260 = 1400; +340 -> 1740 = 10.97% over 1568 -> snap.
        plan = self._plan([59.3, 59.3, 42.142857, 36.428571, 47.857142])
        self.assertEqual(len(plan.bands), 1)
        self.assertEqual(sum(plan.bands[0].col_px), 1568)

    def test_large_overflow_spills_to_new_band(self):
        # px: 420*3+240 = 1500; +420 -> 1920 = 22.4% over -> new band.
        plan = self._plan([59.3, 59.3, 59.3, 33.571428, 59.3])
        self.assertEqual(len(plan.bands), 2)
        self.assertEqual(plan.bands[0].col_px, [420, 420, 420, 240])
        self.assertEqual(plan.bands[1].cols, [5])

    def test_wrap_lines(self):
        # Default 64px column -> 55px content: 7 chars fit on one line,
        # 10 need two, 40 clamp at three.
        for text_len, lines in [(7, 1), (10, 2), (40, 3)]:
            plan = self._plan([None], n_rows=1, text_len=text_len)
            self.assertEqual(
                plan.bands[0].row_px[1], mesh_mod.LINE_PX * lines, f"len={text_len}"
            )

    def test_custom_row_height_wins(self):
        sheet = _sheet({1: {1: "abc"}}, row_heights={1: 30.0})
        plan = mesh_mod.plan_sheet_mesh(sheet, None)
        self.assertEqual(plan.bands[0].row_px[1], 40)

    def test_orientation(self):
        self.assertEqual(self._plan([None, None], n_rows=40).orientation, "portrait")
        self.assertEqual(self._plan([None, None], n_rows=5).orientation, "landscape")
        # Wide sheets stay landscape regardless of row count.
        self.assertEqual(self._plan([59.3] * 4, n_rows=40).orientation, "landscape")

    def test_y_banding_and_header_reservation(self):
        # One narrow column with many rows goes portrait (tile_h 1568).
        plan = self._plan([None], n_rows=100, header_row=1)
        self.assertEqual(plan.orientation, "portrait")
        band = plan.bands[0]
        self.assertEqual(band.header_px, mesh_mod.LINE_PX)
        capacity = plan.tile_h - band.header_px - mesh_mod.TILE_SAFETY_PX
        per_tile = capacity // mesh_mod.LINE_PX  # 69
        self.assertEqual(band.row_band_starts[0], 2)  # header excluded
        self.assertEqual(band.row_band_starts[1], 2 + per_tile)
        self.assertEqual(len(band.row_band_starts), -(-99 // per_tile))

    def test_empty_sheet_yields_no_plan(self):
        self.assertIsNone(mesh_mod.plan_sheet_mesh(_sheet({}), None))


class BuildChunksTests(SimpleTestCase):
    def _model(self, sheets):
        from documents.services.spreadsheets.model import WorkbookModel

        return WorkbookModel(sheets=sheets, skipped_sheets=[], hidden_sheets=[])

    def _headers(self, sheet):
        return {sheet.index: detect_headers(sheet)}

    def test_chunk_zero_and_labelled_rows(self):
        sheet = _sheet(
            {1: {1: "Number", 2: "Project name"},
             2: {1: "202501007", 2: "Ultra-Performance AM"},
             3: {1: "202501008", 2: "Beta"}},
            auto_filter=(1, 1, 3, 2),
        )
        model = self._model([sheet])
        out = chunks_mod.build_spreadsheet_chunks(
            model, "Prosjektliste.xlsm", self._headers(sheet), {0: "Project list."}
        )
        self.assertEqual(out[0]["heading"], "Workbook overview")
        self.assertIn("Prosjektliste.xlsm", out[0]["text"])
        self.assertIn("Columns: Number, Project name", out[0]["text"])
        self.assertEqual(len(out), 2)
        body = out[1]
        self.assertIn("Prosjektliste.xlsm. Sheet 'S': Project list. Rows 2–3.", body["text"])
        self.assertIn("Row 2 — Number: 202501007 | Project name: Ultra-Performance AM", body["text"])
        self.assertEqual(body["heading"], "Sheet: S")
        self.assertEqual(body["source_page_start"], 0)
        self.assertEqual(body["source_offset_start"], 2)
        self.assertEqual(body["source_offset_end"], 3)
        # Bare ALL-CAPS / numeric data survives (no clean_extracted_text here).
        self.assertIn("202501007", body["text"])

    @override_settings(XLSX_ROWS_PER_CHUNK_MAX=2)
    def test_row_cap_and_atomicity(self):
        rows = {1: {1: "H"}}
        rows.update({r: {1: f"value-{r}"} for r in range(2, 9)})
        sheet = _sheet(rows, auto_filter=(1, 1, 8, 1))
        out = chunks_mod.build_spreadsheet_chunks(self._model([sheet]), "f.xlsx",
                                                  self._headers(sheet), {})
        body = out[1:]
        self.assertEqual(len(body), 4)  # 7 data rows / 2 per chunk
        for chunk in body:
            row_lines = [ln for ln in chunk["text"].splitlines() if ln.startswith("Row ")]
            self.assertLessEqual(len(row_lines), 2)
            for line in row_lines:
                self.assertIn("value-", line)  # rows never split mid-line

    @override_settings(TARGET_CHUNK_TOKENS=30)
    def test_token_budget_splits(self):
        rows = {r: {1: "word " * 20} for r in range(1, 6)}
        sheet = _sheet(rows)
        sheet.type_profile = [(r, 1, 1) for r in range(1, 6)]
        out = chunks_mod.build_spreadsheet_chunks(self._model([sheet]), "f.xlsx",
                                                  self._headers(sheet), {})
        self.assertGreater(len(out), 2)

    def test_empty_workbook_still_yields_overview(self):
        sheet = _sheet({}, name="Charts")
        out = chunks_mod.build_spreadsheet_chunks(self._model([sheet]), "charts.xlsx",
                                                  self._headers(sheet), {})
        self.assertEqual(len(out), 1)
        self.assertIn("no cell data", out[0]["text"])

    def test_workbook_to_markdown(self):
        sheet = _sheet(
            {1: {1: "Name", 2: "Amount"}, 2: {1: "Alpha", 2: "1"}, 3: {1: "Be|ta", 2: "2"}},
            auto_filter=(1, 1, 3, 2),
        )
        md = chunks_mod.workbook_to_markdown(self._model([sheet]))
        self.assertIn("## Sheet: S", md)
        self.assertIn("| Name | Amount |", md)
        self.assertIn("| Be\\|ta | 2 |", md)

    def test_workbook_to_markdown_row_cap(self):
        rows = {r: {1: f"v{r}"} for r in range(1, 12)}
        sheet = _sheet(rows)
        sheet.type_profile = [(r, 1, 1) for r in range(1, 11)]
        md = chunks_mod.workbook_to_markdown(self._model([sheet]), max_rows_per_sheet=5)
        self.assertIn("more rows not shown", md)


class RenderHtmlTests(SimpleTestCase):
    """build_band_html is pure — geometry must come verbatim from the plan."""

    def _sheet_and_plan(self, n_rows=100):
        rows = {1: {1: "Number", 2: "Name"}}
        rows.update({r: {1: str(r), 2: f"name-{r}"} for r in range(2, n_rows + 1)})
        sheet = _sheet(rows, auto_filter=(1, 1, n_rows, 2))
        info = detect_headers(sheet)
        plan = mesh_mod.plan_sheet_mesh(sheet, info.header_row)
        return sheet, plan

    def test_geometry_comes_from_the_plan(self):
        from documents.services.spreadsheets.render import build_band_html

        sheet, plan = self._sheet_and_plan()
        html = build_band_html(sheet, plan, 0)
        band = plan.bands[0]
        self.assertIn(f"size: {plan.tile_w}px {plan.tile_h}px", html)
        for px in band.col_px:
            self.assertIn(f'<col style="width:{px}px"/>', html)
        # Every y-band is one table; the header row is re-emitted on each
        # (WeasyPrint does not repeat <thead> across pages) and every table
        # after the first starts a new page.
        n_tables = html.count("<table")
        self.assertEqual(n_tables, len(band.row_band_starts))
        self.assertEqual(html.count(">Number<"), n_tables)
        self.assertEqual(html.count('<table class="pb">'), n_tables - 1)
        self.assertIn("page-break-before: always", html)

    def test_y_limit_renders_only_top_tiles(self):
        from documents.services.spreadsheets.render import build_band_html

        sheet, plan = self._sheet_and_plan()
        self.assertGreater(len(plan.bands[0].row_band_starts), 1)
        html = build_band_html(sheet, plan, 0, y_limit=1)
        self.assertEqual(html.count("<table"), 1)

    def test_merged_cells_render_as_colspan(self):
        from documents.services.spreadsheets.render import build_band_html

        sheet = _sheet({1: {1: "Title"}, 2: {1: "a", 2: "b", 3: "c"}},
                       merged=[(1, 1, 1, 3)])
        plan = mesh_mod.plan_sheet_mesh(sheet, None)
        html = build_band_html(sheet, plan, 0)
        self.assertIn('colspan="3"', html)

    def test_cf_fill_and_escaping(self):
        from documents.services.spreadsheets.render import build_band_html

        sheet = _sheet({1: {1: "<b>&x", 2: "BAD"}})
        sheet.cf_fills[(1, 2)] = "#FFC000"
        plan = mesh_mod.plan_sheet_mesh(sheet, None)
        html = build_band_html(sheet, plan, 0)
        self.assertIn("&lt;b&gt;&amp;x", html)
        self.assertIn("background:#FFC000", html)


def _weasyprint_available() -> bool:
    from chat.pdf_export import weasyprint_available

    return weasyprint_available()


class RenderRasterTests(SimpleTestCase):
    """Real WeasyPrint + pypdfium2 rasterisation — runs wherever the native
    deps exist (verified working on the Windows dev box and on staging)."""

    @unittest.skipUnless(_weasyprint_available(), "WeasyPrint native deps unavailable")
    def test_band_renders_exact_tiles(self):
        from documents.services.spreadsheets.render import band_row_groups, render_band

        rows = {1: {1: "Number", 2: "Name"}}
        rows.update({r: {1: str(r), 2: f"name-{r}"} for r in range(2, 160)})
        sheet = _sheet(rows, auto_filter=(1, 1, 159, 2))
        plan = mesh_mod.plan_sheet_mesh(sheet, 1)
        expected = len(band_row_groups(sheet, plan, 0))
        self.assertGreater(expected, 1)

        tiles = render_band(sheet, plan, 0)
        self.assertEqual(len(tiles), expected)
        for _png, width, height in tiles:
            self.assertEqual((width, height), (plan.tile_w, plan.tile_h))
        # y_limit renders only the top tile.
        self.assertEqual(len(render_band(sheet, plan, 0, y_limit=1)), 1)


class ReadsTests(SimpleTestCase):
    def test_parse_col_spec(self):
        from documents.services.spreadsheets.reads import parse_col_spec

        self.assertEqual(parse_col_spec("A,C-F"), [1, 3, 4, 5, 6])
        self.assertEqual(parse_col_spec("b"), [2])
        with self.assertRaises(ValueError):
            parse_col_spec(",")

    def test_find_and_read_rows_stream_formatted_values(self):
        from openpyxl import Workbook

        from documents.services.spreadsheets.reads import find_in_workbook, read_cell, read_rows

        wb = Workbook()
        ws = wb.active
        ws.title = "S"
        ws.append(["Name", "Amount"])
        ws.append(["Alpha", 1234.5])
        ws["B2"].number_format = "#,##0.00"
        hidden = wb.create_sheet("Hidden")
        hidden["A1"] = "Alpha"
        hidden.sheet_state = "hidden"

        with tempfile.TemporaryDirectory() as tmpdir:
            path = _save(wb, tmpdir)
            hits, truncated = find_in_workbook(path, "alpha")
            self.assertFalse(truncated)
            # Hidden sheets are never scanned.
            self.assertEqual([(h["sheet"], h["row"], h["col"]) for h in hits], [("S", 2, 1)])

            hits, truncated = find_in_workbook(path, "1,234.50")
            self.assertEqual(len(hits), 1)  # formatted text is what is searched

            rows, truncated = read_rows(path, "S", 2, 2)
            self.assertEqual(rows, [(2, [(1, "Alpha"), (2, "1,234.50")])])

            value, cells = read_cell(path, "S", 2, 2)
            self.assertEqual(value, "1,234.50")
            self.assertEqual(dict(cells)[1], "Alpha")

            with self.assertRaises(ValueError):
                read_rows(path, "Missing", 1, 2)


class ManifestTests(SimpleTestCase):
    def _manifest(self):
        sheet = _sheet(
            {1: {1: "Name", 2: "Amount"}, 2: {1: "a", 2: "1"}, 3: {1: "b", 2: "2"}},
            auto_filter=(1, 1, 3, 2), hidden_cols={3}, hidden_rows={9, 10, 12},
        )
        info = detect_headers(sheet)
        plan = mesh_mod.plan_sheet_mesh(sheet, info.header_row)
        from documents.services.spreadsheets.model import WorkbookModel

        model = WorkbookModel(sheets=[sheet], skipped_sheets=["Extra"], hidden_sheets=["Hid"])
        return manifest_mod.build_manifest(
            model, {0: info}, {0: info}, {0: plan}, {0: "desc"}
        )

    def test_shape_and_json_round_trip(self):
        import json

        manifest = self._manifest()
        manifest = json.loads(json.dumps(manifest))  # must be JSON-clean
        self.assertTrue(manifest_mod.is_spreadsheet_manifest(manifest))
        self.assertEqual(manifest["renderer_rev"], mesh_mod.RENDERER_REV)
        entry = manifest["sheets"][0]
        self.assertEqual(entry["header"]["row"], 1)
        self.assertEqual(entry["header"]["signal"], "autofilter")
        self.assertFalse(entry["header"]["vision_adjusted"])
        self.assertEqual(entry["header"]["labels"]["1"], "Name")
        self.assertEqual(entry["hidden_cols"], ["C"])
        self.assertEqual(entry["hidden_rows"], [[9, 10], [12, 12]])
        self.assertEqual(entry["mesh"]["bands"][0]["cols"], ["A", "B"])
        self.assertEqual(manifest["skipped_sheets"], ["Extra"])

    def test_sheet_lookup_and_row_helpers(self):
        manifest = self._manifest()
        self.assertIsNotNone(manifest_mod.get_sheet_entry(manifest, "s"))
        self.assertIsNotNone(manifest_mod.get_sheet_entry(manifest, 0))
        self.assertIsNone(manifest_mod.get_sheet_entry(manifest, "missing"))
        entry = manifest_mod.get_sheet_entry(manifest, None)
        self.assertTrue(manifest_mod.row_is_hidden(entry, 9))
        self.assertFalse(manifest_mod.row_is_hidden(entry, 11))
        self.assertEqual(manifest_mod.hidden_cols_set(entry), {3})

    def test_tiles_covering_rows(self):
        entry = {
            "mesh": {
                "bands": [
                    {"row_band_starts": [2, 40, 80]},
                    {"row_band_starts": [2, 50]},
                ]
            }
        }
        self.assertEqual(manifest_mod.tiles_covering_rows(entry, 45, 45), [(0, 1), (1, 0)])
        self.assertEqual(
            manifest_mod.tiles_covering_rows(entry, 2, 85),
            [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1)],
        )
        self.assertEqual(manifest_mod.tiles_covering_rows(entry, 1, 1), [])
