# Generated by Django 6.0.1 on 2026-03-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='cached_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='provider_model_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='reasoning_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='response_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='stop_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
