# Generated by Django 6.0.1 on 2026-03-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_add_tracing_and_response_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmcalllog',
            name='raw_prompt',
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='tools',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
