# Generated by Django 6.0.1 on 2026-05-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_remove_llmcalllog_raw_prompt_llmcalllog_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='cache_write_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
