# Generated by Django 6.0.1 on 2026-06-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_add_cache_write_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcalllog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('cancelled', 'Cancelled')], db_index=True, default='success', max_length=32),
        ),
    ]
