# Generated by Django 6.0.1 on 2026-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_alter_llmcalllog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('org_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tool_name', models.CharField(db_index=True, max_length=64)),
                ('response_bytes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OPS Usage Log',
                'verbose_name_plural': 'OPS Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org_id', 'created_at'], name='ops_usage_org_created_idx')],
            },
        ),
    ]
