# Generated by Django 6.0.1 on 2026-09-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_opsusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='prune_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='tool_call_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='tool_result_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
