# Generated by Django 6.0.1 on 2026-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_llmcalllog_prune_count_llmcalllog_tool_call_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='estimated_input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
