# Generated by Django 6.0.1 on 2026-09-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_llmcalllog_estimated_input_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='edit_point_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='edit_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='thinking_dropped_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
