# Generated by Django 6.0.1 on 2026-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0009_llmcalllog_edit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsusagelog',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='opsusagelog',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opsusagelog',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='opsusagelog',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='opsusagelog',
            name='http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsusagelog',
            name='outcome',
            field=models.CharField(choices=[('ok', 'Ok'), ('no_results', 'No Results'), ('error', 'Error')], db_index=True, default='ok', max_length=16),
        ),
        migrations.AddField(
            model_name='opsusagelog',
            name='query',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='opsusagelog',
            name='request_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
