# Generated by Django 6.0.1 on 2026-02-20 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('is_stream', models.BooleanField(default=False)),
                ('request_kwargs', models.JSONField(blank=True, default=dict)),
                ('prompt_hash', models.CharField(blank=True, max_length=64)),
                ('prompt_preview', models.TextField(blank=True)),
                ('user_message_preview', models.CharField(blank=True, max_length=300)),
                ('provider_response_id', models.CharField(blank=True, max_length=255, null=True)),
                ('response_model', models.CharField(blank=True, max_length=255, null=True)),
                ('response_preview', models.TextField(blank=True)),
                ('response_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_response_payload', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('cost_source', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('logging_failed', 'Logging failed')], db_index=True, default='success', max_length=32)),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('provider_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Call Log',
                'verbose_name_plural': 'LLM Call Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='llm_calllog_created_idx'), models.Index(fields=['user', 'created_at'], name='llm_calllog_user_created_idx'), models.Index(fields=['model', 'created_at'], name='llm_calllog_model_created_idx')],
            },
        ),
    ]
